FROM python:3.11-slim

WORKDIR /app

# System packages for scipy, numpy, pandas
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Requirements
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy simulation code
COPY sim_rl /app/sim_rl

# Copy data pipeline (important!!)
COPY data_pipeline /app/data_pipeline

CMD ["bash"]
